language: r
cache: packages
r:
  - oldrel
  - release
r_packages:
  - devtools
bioc_required: true
bioc_use_devel: true
sudo: false
os:
  - linux
  - osx

after_success:
- Rscript -e 'library(covr); codecov()'